export default {
  common: {
    delete: 'Delete',
    open: 'Open',
    create: 'Create',
    confirm: 'Confirm',
    cancel: 'Cancel',
    close: 'Close',
    detail: 'Detail',
    share: 'Share',
    send: 'Send',
    skip: 'Skip',
    back: 'Back',
    notAssigned: 'Not assigned',
    lastUpdates: 'Last updated',
    clearAll: 'Clear all',
    or: 'or',
    code: 'Code',
    help: 'Help',
    settings: 'Settings',
    createIssue: 'Create issue',
    noResults: 'No results',
    summary: 'Summary',
    title: 'Title',
    description: 'Description',
    giveReview: 'Give review',
    addTitle: 'Add title',
    changeTitle: 'Change title',
    activity: 'Activity',
    addComment: 'Add comment...',
    advice: 'Advice',
    press: 'press',
    toAddComment: 'to add comment',
    edited: 'Edited',
    edit: 'Edit',
    created: 'Created',
    updateDate: 'Update date',
    thereNoAnything: "There's no anything",
    search: 'Search',
  },

  work: {
    title: 'Your work',
    recent: 'Recent projects',
    all: 'All projects',
    open: 'Open projects page',
    openProject: 'Open project',
    noProjects: 'No projects',
    boards: '0 boards | {n} board | {n} boards',
  },

  email: {
    confirmation: 'Email confirmation',
    confirmSuccess: 'You successfully confirmed Email',
    confirmResend: 'Mail was sent on your email',
    confirmError:
      'Something went wrong and the email was not confirmed. Perhaps the confirmation link has expired or the Email has already been confirmed',
    resend: 'Resend',
  },

  project: {
    project: 'Project',
    projects: 'Projects',

    kanbanDescription: 'Get a visual idea of working on a project thanks to simple tips and a functional whiteboard.',
    scrumDescription: 'Achieve your goals faster with a modern whiteboard and backlog.',
    companyManage: 'Software managed by the company',
    teamManage: 'Software managed by the team',

    chooseType: 'Choose project type',
    create: 'Create project',
    delete: 'This project and its configuration will be permanently deleted.',
    settings: 'Project settings',
    trash: 'Move to trash',

    board: 'Board',
    softwareDevProject: 'Software Development Project',
    companyType: 'This is a project managed by a company',

    automation: 'Automation',
    markBoard: 'Mark board',
    newVersion: 'New version',
    enterNameTeamOrEmail: 'Enter name, team or email',
    enterMessage: 'Enter message',
    copyLink: 'Copy link',
    onlyMyTasks: 'Only my tasks',
    release: 'Release',

    noCurrentIssues: 'No visible current tasks',
    createIssue: 'Create issue',
    orCheck: 'or check',
    boardSettings: 'board settings',
    importIssues: 'Import issues',
    configureFields: 'Configure fields',

    assigned: 'Assigned',
    marks: 'Marks',
    addMarks: 'Add marks',
    assignToMe: 'Assign to me',
    changeIssueType: 'change issue type',
    editAssigned: 'Edit assigned',
    author: 'Author',
    editAuthor: 'Edit author',
    openSettings: 'Open settings dialog',
    configure: 'Configure',
    deleteComment: 'Delete comment?',
    deleteCommentFrom: 'Delete comment from {name}',

    issueType: {
      issueType: 'Issue type',
      bug: 'Bug',
      task: 'Task',
      history: 'History',
      investigation: 'Investigation',
    },
    issuePriority: {
      priority: 'Priority',
      edit: 'Edit priority',
      lowest: 'Lowest',
      low: 'Low',
      medium: 'Medium',
      high: 'High',
      urgent: 'Urgent',
    },
  },

  access: {
    access: 'Access',
    private: 'Private',
    privateDescription:
      'Только администраторы и пользователи, добавленные в проект, могут выполнять поиск, создавать и редактировать его задачи.',
    limited: 'Limited',
    limitedDescription:
      'Любой пользователь может выполнять поиск, просматривать и комментировать. Только пользователи, добавленные в проект, могут создавать и редактировать его задачи.',
    opened: 'Opened',
    openedDescription:
      'Любой пользователь может выполнять поиск, просматривать, комментировать, создавать и редактировать задачи.',
  },

  people: {
    membersNoCount: 'members',
    members: '0 members | {n} member | {n} members',
    yourNewTeam: 'Your new team!',
    createTeam: 'Create new team',
    addTeamMembers: 'Add team members',
    deleteTeam: 'Delete team?',
    deleteTeamText: 'Delete team <span class="text-weight-bold"> {name} </span> with {number} members?',
    activityAccess: 'Other users will only see the objects they have access to.',
    activityYourLast: 'It shows all the objects that you have created, changed or commented on in the last 90 days.',
    activityUserLast:
      'It shows all the objects that the user has created, changed or commented on in the last 90 days.',
    activityTeamLast:
      'It shows all the objects that the team has created, changed or commented on in the last 90 days.',
    manageAccount: 'Manage account',

    info: 'info',
    contactInfo: 'contact info',
    yourPosition: 'Your position',
    position: 'Position',
    yourDepartment: 'Your department',
    department: 'Department',
    yourOrganisation: 'Your oOrganisation',
    organisation: 'Organisation',
    yourLocation: 'Your location',
    location: 'Location',
  },

  user: {
    displayName: 'Display name',
    username: 'Username',
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm password',
    profile: 'Profile',
    displayNameUsernameOrEmail: 'Their display name, username or email',
    max10Users: 'You can invite no more than 10 users at a time.',
  },

  auth: {
    register: 'Register',
    registerJiraAccount: 'Create new Jira account',
    resetPassword: 'Reset password',
    signIn: 'Sign in',
    signOut: 'Sign out',
    signInJira: 'Sign in Jira',
    scanQrCode: 'Scan the QR code using the Google Authenticator app and enter the code in the field below',
    enter2FaCode: 'Enter the code from the Google Authenticator app',
    incorrect2FaCode: 'Invalid code, try again',
    recoverPassword: 'Recover the password from the Jira account',
    sendEmail: 'Send Email',
    passwordsNotMatch: 'Passwords not match',
  },

  validation: {
    required: 'Required field',
    incorrectEmailFormat: 'Incorrect Email format',
    usernameTaken: 'Username already taken',
    emailTaken: 'Such email already taken',
    minChars: 'Минимум 0 символов | Минимум {n} символ | Минимум {n} символа | Минимум {n} символов',
    maxChars: 'Максимум 0 символов | Максимум {n} символ | Максимум {n} символа | Максимум {n} символов',
    upToChars: 'До 0 символов | До {n} символа | До {n} символов | До {n} символов',
  },

  tabs: {
    work: 'Work',
    projects: 'Projects',
    filters: 'Filters',
    dashboards: 'Dashboards',
    people: 'People',
    apps: 'Apps',
  },

  notification: {
    notifications: 'Notifications',
    showUnread: 'Show only unread',

    noLast30Days: 'No notifications for the last 30 days',
    noUnreadLast30Days: 'All notifications for the last 30 days have been read',

    markRead: 'Mark as read',
    markAllRead: 'Mark all as read',
    markUnread: 'Mark as unread',

    typeTitles: {
      news: 'News on the Jira app',
      issueAssign: 'You have been assigned a task',
      issueWatchUpdate: 'The observed task has been updated',
    },
  },

  date: {
    secondsAgo: '0 секунд назад | {n} секунду назад | {n} секунды назад | {n} секунд назад',
    minutesAgo: '0 минут назад | {n} минуту назад | {n} минуты назад | {n} минут назад',
    hoursAgo: '0 час назад | {n} час назад | {n} часа назад | {n} часов назад',
    daysAgo: '0 день назад| {n} день назад | {n} дня назад | {n} дней назад',
    monthsAgo: '0 месяц назад | {n} месяц назад | {n} месяца назад | {n} месяцев назад',

    today: 'Today',
    yesterday: 'Yesterday',
    older: 'Older',
  },

  table: {
    name: 'Name',
    key: 'Key',
    type: 'Type',
    template: 'Template',
    leader: 'Leader',
    group: 'Group',
    owner: 'Owner',
    resetFilters: 'Reset filters',
  },
};